namespace DBMigrator.Core.Models.Configuration;

public class MigratorConfig
{
    public string ConnectionString { get; set; } = string.Empty;
    public string MigrationsPath { get; set; } = "./migrations";
    public string Environment { get; set; } = "development";
    public string Schema { get; set; } = "public";
    public bool AutoGenerateDown { get; set; } = true;
    public bool CreateBackupBeforeMigration { get; set; } = true;
    public string BackupPath { get; set; } = "./backups";
    public int CommandTimeout { get; set; } = 30;
    public bool VerboseOutput { get; set; } = false;

    public static MigratorConfig Default => new()
    {
        ConnectionString = string.Empty,
        MigrationsPath = "./migrations",
        Environment = "development",
        Schema = "public",
        AutoGenerateDown = true,
        CreateBackupBeforeMigration = true,
        BackupPath = "./backups",
        CommandTimeout = 30,
        VerboseOutput = false
    };
}